[package]
name    = "example-using-ncollide"
version = "0.0.0"
authors = [ "You" ]

[dependencies.ncollide]
git = "http://github.com/sebcrozet/ncollide"

[[bin]]
name = "example"
path = "./example.rs"
