[package]
name    = "ncollide-user-guide-primitives"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[dependencies.kiss3d]
git = "http://github.com/sebcrozet/kiss3d"

[[bin]]
name = "primitives"
path = "./primitives.rs"
