[package]
name    = "example-using-ncollide2d"
version = "0.0.0"
authors = [ "You" ]

[dependencies.ncollide2df32]
git = "http://github.com/sebcrozet/ncollide"

[[bin]]
name = "example2d"
path = "./example2d.rs"
